### ISSUE TITLE
CSS について

### ISSUE THREAD

**Issue by ygkn** [xryuseix/xryuseix.github.io#4]
現在以下を併用してそう

- Tailwind CSS
- normalize CSS
- 独自 CSS (`src/style.css`)

Tailwind 使うんだったら normalize CSS いらんし、Tailwind と独自 CSS 組み合わせると破綻しがちなので、以下のいずれかをやってね

- Tailwind に寄せる
- normalize CSS +　独自 CSS 使う
- その他のなんか使う
  - Chakra UI とか

**Comment by xryuseix** [comment]
直した
